In [1]:
#importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 fro

In [60]:
#Loading Data
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [61]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
Loan_ID              614 non-null object
Gender               601 non-null object
Married              611 non-null object
Dependents           599 non-null object
Education            614 non-null object
Self_Employed        582 non-null object
ApplicantIncome      614 non-null int64
CoapplicantIncome    614 non-null float64
LoanAmount           592 non-null float64
Loan_Amount_Term     600 non-null float64
Credit_History       564 non-null float64
Property_Area        614 non-null object
Loan_Status          614 non-null object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.4+ KB


In [62]:
train.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [63]:
train.tail()

Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

# Chesking Missing Values

In [64]:
#Chesking Null Values
train.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [65]:
#Replacing Missing values
train.Gender = train.Gender.fillna(train.Gender.mode()[0])
train.Married = train.Married.fillna(train.Married.mode()[0])
train.Dependents = train.Dependents.fillna(train.Dependents.mode()[0])
train.Self_Employed = train.Self_Employed.fillna(train.Married.mode()[0])
train.LoanAmount = train.LoanAmount.fillna(train.LoanAmount.mean())
train.Loan_Amount_Term = train.Loan_Amount_Term.fillna(train.Loan_Amount_Term.mode()[0])
train.Credit_History = train.Credit_History.fillna(train.Credit_History.mode()[0])

In [66]:
train.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [67]:
test.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [68]:
#Replacing Missing values
test.Gender = test.Gender.fillna(test.Gender.mode()[0])
#test.Married = test.Married.fillna(test.Married.mode()[0])
test.Dependents = test.Dependents.fillna(test.Dependents.mode()[0])
test.Self_Employed = test.Self_Employed.fillna(test.Married.mode()[0])
test.LoanAmount = test.LoanAmount.fillna(test.LoanAmount.mean())
test.Loan_Amount_Term = test.Loan_Amount_Term.fillna(test.Loan_Amount_Term.mode()[0])
test.Credit_History = test.Credit_History.fillna(test.Credit_History.mode()[0])


In [69]:
test.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [70]:
# making a copy
train_sam1 = train.copy()
test_sam1 = train.copy()

In [114]:
train = train_sam1.copy()
test = test_sam1.copy()

In [115]:
train.drop(['Loan_ID'], axis=1,inplace=True)
test.drop(['Loan_ID'],axis=1,inplace=True)

# Building Models

In [116]:
X = train.drop('Loan_Status',axis=1)
train = pd.get_dummies(train, drop_first= True)
test = pd.get_dummies(test, drop_first= True)

In [117]:
X=pd.get_dummies(X)

In [118]:
y = train.Loan_Status_Y

In [119]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

# Logistic Regression

In [120]:
from sklearn.linear_model import LogisticRegression
logi = LogisticRegression()
logi.fit(x_train,y_train)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [121]:
pred_test = logi.predict(x_test)

In [122]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
accuracy_score(y_test,pred_test)

0.8455284552845529

In [123]:
confusion_matrix(y_test,pred_test)

array([[15, 19],
       [ 0, 89]], dtype=int64)

In [154]:
from sklearn.linear_model import LogisticRegression
Logistic = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True,
                            intercept_scaling=1, class_weight=None, 
                            random_state=None, solver='liblinear', max_iter=100,
                            multi_class='ovr', verbose=2)
Logistic.fit(x_train, y_train)

[LibLinear]

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=2, warm_start=False)

In [155]:
# Predicting the Test set results
y_pred = Logistic.predict(x_test)

# Making the Confusion Matrix 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
np.set_printoptions(precision=2)

In [156]:
cm

array([[15, 19],
       [ 0, 89]], dtype=int64)

In [157]:
accuracy_score(y_test,pred_test)

0.8455284552845529

# Random Forest

In [125]:
from sklearn.ensemble import RandomForestClassifier
Random = RandomForestClassifier(n_estimators=10, criterion='gini', max_depth=None, min_samples_split=2,
                               min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto',
                               max_leaf_nodes=None, bootstrap=True, oob_score=False, n_jobs=1, 
                               random_state=None, verbose=0)
Random.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [127]:
# Predicting the Test set results
y_pred = Random.predict(x_test)

# Making the Confusion Matrix 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
np.set_printoptions(precision=2)

In [128]:
cm

array([[17, 17],
       [ 7, 82]], dtype=int64)

In [129]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.50      0.59        34
           1       0.83      0.92      0.87        89

   micro avg       0.80      0.80      0.80       123
   macro avg       0.77      0.71      0.73       123
weighted avg       0.80      0.80      0.79       123



# Ada Boost

In [143]:
from sklearn.ensemble import AdaBoostClassifier
ADA = AdaBoostClassifier(base_estimator=None, n_estimators=200, learning_rate=1.0)
ADA.fit(x_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=200, random_state=None)

In [145]:
y_pred = ADA.predict(x_test)

# Making the Confusion Matrix 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
np.set_printoptions(precision=2)
cm

array([[19, 15],
       [14, 75]], dtype=int64)

# Gradient Boosting

In [147]:
from sklearn.ensemble import GradientBoostingClassifier
GradientBoo = GradientBoostingClassifier(loss='deviance', learning_rate=0.1, n_estimators=200, subsample=1.0,
                                   min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
                                   max_depth=3,
                                   init=None, random_state=None, max_features=None, verbose=0)
GradientBoo.fit(x_train, y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=200,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False)

In [149]:
y_pred = GradientBoo.predict(x_test)

# Making the Confusion Matrix 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
np.set_printoptions(precision=2)
cm

array([[17, 17],
       [12, 77]], dtype=int64)

# Hyper parameter optimization using Randomized search

In [138]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

In [150]:
adaHyperParams = {'n_estimators': [10,50,100,200,420]}
gridSearchAda = RandomizedSearchCV(estimator=ADA, param_distributions=adaHyperParams, n_iter=5,
                                   scoring='roc_auc', fit_params=None, cv=None, verbose=2).fit(x_train, y_train)
gridSearchAda.best_params_, gridSearchAda.best_score_

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


Fitting 3 folds for each of 5 candidates, totalling 15 fits
[CV] n_estimators=10 .................................................
[CV] .................................. n_estimators=10, total=   0.0s
[CV] n_estimators=10 .................................................
[CV] .................................. n_estimators=10, total=   0.0s
[CV] n_estimators=10 .................................................
[CV] .................................. n_estimators=10, total=   0.0s
[CV] n_estimators=50 .................................................
[CV] .................................. n_estimators=50, total=   0.0s
[CV] n_estimators=50 .................................................
[CV] .................................. n_estimators=50, total=   0.0s
[CV] n_estimators=50 .................................................
[CV] .................................. n_estimators=50, total=   0.0s
[CV] n_estimators=100 ................................................
[CV] ............

[Parallel(n_jobs=1)]: Done  15 out of  15 | elapsed:    3.5s finished


({'n_estimators': 10}, 0.7383077470596204)

In [153]:
bHyperParams = {'loss' : ['deviance', 'exponential'],
                 'n_estimators': randint(10, 500),
                 'max_depth': randint(1,10)}
gridSearchGB = RandomizedSearchCV(estimator=GradientBoo, param_distributions=bHyperParams, n_iter=10,
                                   scoring='roc_auc', fit_params=None, cv=None, verbose=2).fit(x_train, y_train)
gridSearchGB.best_params_, gridSearchGB.best_score_

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 3 folds for each of 10 candidates, totalling 30 fits
[CV] loss=deviance, max_depth=7, n_estimators=171 ....................
[CV] ..... loss=deviance, max_depth=7, n_estimators=171, total=   0.3s
[CV] loss=deviance, max_depth=7, n_estimators=171 ....................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s


[CV] ..... loss=deviance, max_depth=7, n_estimators=171, total=   0.3s
[CV] loss=deviance, max_depth=7, n_estimators=171 ....................
[CV] ..... loss=deviance, max_depth=7, n_estimators=171, total=   0.4s
[CV] loss=exponential, max_depth=9, n_estimators=365 .................
[CV] .. loss=exponential, max_depth=9, n_estimators=365, total=   0.6s
[CV] loss=exponential, max_depth=9, n_estimators=365 .................
[CV] .. loss=exponential, max_depth=9, n_estimators=365, total=   0.5s
[CV] loss=exponential, max_depth=9, n_estimators=365 .................
[CV] .. loss=exponential, max_depth=9, n_estimators=365, total=   0.5s
[CV] loss=deviance, max_depth=7, n_estimators=207 ....................
[CV] ..... loss=deviance, max_depth=7, n_estimators=207, total=   0.4s
[CV] loss=deviance, max_depth=7, n_estimators=207 ....................
[CV] ..... loss=deviance, max_depth=7, n_estimators=207, total=   0.4s
[CV] loss=deviance, max_depth=7, n_estimators=207 ....................
[CV] .

[Parallel(n_jobs=1)]: Done  30 out of  30 | elapsed:    8.0s finished


({'loss': 'exponential', 'max_depth': 9, 'n_estimators': 365},
 0.7651842195995445)